# Generated by Django 4.2 on 2023-04-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_scope_articles_alter_scope_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='is_name',
            new_name='is_main',
        ),
    ]
